spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/WopiHost
    driver-class-name: org.postgresql.Driver
    username: viratech
    password: aammiinn

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

wopi:
  username: sysadmin
  password: sysadmin
  serverEditorFrameUrl: office.naadsecure.ir
  officeWordEditorFrameUrl: office.naadsecure.ir
  powerPointEditorFrameUrl: office.naadsecure.ir
  excelEditorFrameUrl: office.naadsecure.ir
  fileDirectoryPath: D:\\